name: Release window
run-name: Auto relase for window version 🚀
on: 
  push:
    branches:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, Windows, X64, laptop]
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.PAT_TOKEN }}"
          prerelease: true
          files: |
            LICENSE.txt
            *.jar
          draft: true
